version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_KEY=${NEXT_PUBLIC_API_KEY}
        - NEXT_PUBLIC_SALT=${NEXT_PUBLIC_SALT}
        - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
        - NEXT_PUBLIC_BASE_URL_CHATBOT=${NEXT_PUBLIC_BASE_URL_CHATBOT}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
